name: Build and Push Docker Image (Multi-Arch)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        options: --privileged

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU for multi-arch support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64, amd64

      # Step 3: Log in to Docker Hub or GitHub Container Registry (GHCR)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
